# -*- coding: utf-8 -*-
"""Motor de reglas para ruta optima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sEMQ3dmNmRwC-JrSo8gc3_h59b82U5JO

Ruta mas rapida de punto A y punto B
"""

import networkx as nx
import matplotlib.pyplot as plt

destinos_grafo = nx.Graph()

destinos_grafo.add_node('portalAmericas')
destinos_grafo.add_node('ricaurte')
destinos_grafo.add_node('portalNorte')
destinos_grafo.add_node('avJimenez')
destinos_grafo.add_node('MuseoDelOro')
destinos_grafo.add_node('Calle22')

destinos_grafo.add_edge('portalAmericas', 'ricaurte', time=29)
destinos_grafo.add_edge('ricaurte', 'portalNorte', time=49)
destinos_grafo.add_edge('portalAmericas', 'avJimenez', time=34)
destinos_grafo.add_edge('avJimenez', 'portalNorte', time=48)
destinos_grafo.add_edge('portalAmericas', 'MuseoDelOro', time=36)
destinos_grafo.add_edge('MuseoDelOro', 'portalNorte', time=50)
destinos_grafo.add_edge('portalAmericas', 'Calle22', time=41)
destinos_grafo.add_edge('Calle22', 'MuseoDelOro', time=45)
pos = nx.spring_layout(destinos_grafo)
nx.draw(destinos_grafo, pos, with_labels=True, node_color='lightblue', node_size=200, font_size=10)
labels = nx.get_edge_attributes(destinos_grafo, 'time')
nx.draw_networkx_edge_labels(destinos_grafo, pos, edge_labels=labels)
plt.show()
